language: java

before_install:
  - wget https://services.gradle.org/distributions/gradle-6.0.1-bin.zip
  - unzip -qq gradle-6.0.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.0.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

before_script:
  - pwd
  - ls

script:
  - gradle build